before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Sm2yDIuEOXMz12YNOU9y/7b6Txd4EXypxWvx9JGL5LFLKwSvtNF9RanYhQrla5LHhQW3Y+AKQWq8kHnzBBfKWF71Delidv4uSciGcQv7pPbDmdvFFJMVdBOTZxswn+LV/EOwqYlHYCEaiosOBXBmyKUXq2OKjqomB8fIqqyGymIQ8STSLHfCKD/JxquaE35zTykRpkVRx1BzXEAcYWD0rhqRoHDM3h4aE4buzxeRpHgAl4UvyuOxDS4r5vG82UcI3HvRojR7pDjHL9JTfweI6LJ6j4iTeEd80IUMVTElHUgInz9lJTaoTIyDWQToNaXiHf3xgGJQa0LJFEMIVXWQRTCN0ogqv/SBk9DTdUniJEP13Cq/4E2E3ltXFSTuUOsbZPjhM3cx8bgv9mRbMUCYKYKpIM+b+oyCQaVPj8YTz+ByELNNYRbeJm6m39ALQeqARRP2vqk0AQvEpbxlkX1hHDkZ+NUk1nz73cCwsAedE38lttCA2vtLbrFqWPnsvaV7k7EYBYyJ3dWjyP4ctLl7ztdHE5Pk7cAXAj53uc0SdjWuII6GYtibIg1IsB6SQq9CORHeQLI65+ieT5LVDYUKfX4dmIBYMELAKu+jFB6R74vZB6rfmkS1P2kYmuT82Wn3xFZJKtKAZVuaHOgsDfOGVDcLAvTByOOr0EgotMFrEk0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
